name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *" # Atualiza diariamente
  workflow_dispatch: # Permite rodar o script manualmente

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.MEU_TOKEN_SECRETO }}
          USERNAME: ${{ github.repository_owner }}
      - name: Make background and charts transparent
        run: |
          sed -i -e 's/fill="#00000f"/fill="none"/g' \
                 -e 's/fill="#aaaaaa"/fill="none"/g' \
                 -e 's/fill="#eeeeff"/fill="none"/g' \
                 -e 's/fill="#3178c6"/fill="none"/g' \
                 -e 's/fill="#355570"/fill="none"/g' \
                 -e 's/fill="#4F5D95"/fill="none"/g' \
                 -e 's/fill="#00B4AB"/fill="none"/g' \
                 -e 's/fill="#3572A5"/fill="none"/g' \
                 -e 's/fill="#444444"/fill="none"/g' \
                 -e 's/fill="rgb(255,200,55)"/fill="none"/g' \
                 -e 's/stroke="#00000f"/stroke="none"/g' \
                 profile-3d-contrib/profile-night-rainbow.svg
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Gerado grafico 3D" || echo "Nada novo para commitar"
          git push
