name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *" # Atualiza diariamente
  workflow_dispatch: # Permite rodar o script manualmente

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.MEU_TOKEN_SECRETO }}
          USERNAME: ${{ github.repository_owner }}
      - name: Make background and charts transparent
        run: |
          sed -i -e 's/#00000f/none/g' \
                 -e 's/#aaaaaa/none/g' \
                 -e 's/#eeeeff/none/g' \
                 -e 's/#3178c6/none/g' \
                 -e 's/#355570/none/g' \
                 -e 's/#4F5D95/none/g' \
                 -e 's/#00B4AB/none/g' \
                 -e 's/#3572A5/none/g' \
                 -e 's/#444444/none/g' \
                 -e 's/rgb(255,200,55)/none/g' \
                 -e 's|</svg>|<g transform="translate(1240, 60)"><text font-family="Ubuntu, Helvetica, Arial, sans-serif" font-size="64" font-weight="bold" fill="#ffffff" text-anchor="end" style="filter: drop-shadow(0px 0px 15px rgba(255, 255, 255, 0.9));"><tspan x="0" dy="0">Commit&#39;s</tspan><tspan x="0" dy="70">City</tspan></text></g></svg>|g' \
                 profile-3d-contrib/profile-night-rainbow.svg
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Gerado grafico 3D" || echo "Nada novo para commitar"
          git push
